import arcade

WINDOWTITLE = 'Pong'
WINDOWWIDTH = 1200
WINDOWHEIGHT = 800
LINETHICKNESS = 15
PADDLEHEIGHT = WINDOWHEIGHT / 10
PADDLEOFFSET = 40
FONTSIZE = WINDOWHEIGHT / 8


FPS = 400

BLACK = arcade.color.BLACK
WHITE = arcade.color.WHITE
